name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    runs-on: ubuntu-latest
    container: ghcr.io/homebrew/brew:main
    permissions:
      contents: read
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: brew style --cask jacobwpeng/cursor-cli
      - run: brew audit --cask jacobwpeng/cursor-cli
